AWSTemplateFormatVersion: '2010-09-09'
Transform: "AWS::Serverless-2016-10-31"
Description: "Event Driven Security - Lesson 1 Step 4"

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 6
    Runtime: "python3.6"  
    # Environment:
    #   Variables:
    #     EXAMPLE: value

Parameters:
  WebhookUrl:
    Description: "What webhook should we alert. Testing? Try https://webhook.site/"
    Type: "String"
  AlertRoles:
    Description: "Roles that would should alert when someone assumes them"
    Type: "String"

Resources:
  AssumptionAlertFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: "handler.lambda_handler"
      CodeUri: "./src"
      Environment:
        Variables:
          WEBHOOK_URL: !Ref "WebhookUrl"
          ALERT_ROLES: !Ref "AlertRoles"

